# Generated by Django 4.0.2 on 2022-02-21 18:55

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('image', models.ImageField(default='default-vacancy-pic.png', upload_to='images/vacancy_pics', verbose_name='Фото')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'открытие вакансии',
                'verbose_name_plural': 'Открытие вакансии',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ManyToManyField(blank=True, related_name='permissions_access', to='accounts.Position', verbose_name='Кому разрешено')),
            ],
            options={
                'verbose_name': 'разрешение на страницы руководителей',
                'verbose_name_plural': 'Разрешение на страницы руководителей',
            },
        ),
        migrations.CreateModel(
            name='Dismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО увольняемого')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание / причины увольнения')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('account', models.ForeignKey(blank=True, help_text='Выберите аккаунт увольняемого, если таковой имеется.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'подача на увольнение',
                'verbose_name_plural': 'Подачи на увольнение',
            },
        ),
    ]
