# Generated by Django 4.0.2 on 2022-03-03 08:11

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_alter_department_options_and_more'),
        ('inner_life', '0002_alter_gallery_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'лучший сотрудник',
                'verbose_name_plural': 'Лучшие сотрудники',
            },
        ),
    ]
