# Generated by Django 4.0.2 on 2022-03-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('inner_life', '0003_bestemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestemployee',
            name='access',
            field=models.ManyToManyField(blank=True, to='accounts.Position', verbose_name='Уровень доступа'),
        ),
    ]
