# Generated by Django 4.0.2 on 2022-02-21 18:55

import ckeditor_uploader.fields
import config.validators
import departments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('positioning', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Позиционирование')),
                ('slug', models.SlugField(max_length=100, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='DepartmentReglament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_type', models.CharField(choices=[('position_instruction', 'Должностная инструкция'), ('job_instruction', 'Инструкция по работе')], default='position_instruction', max_length=255, verbose_name='Тип')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('access', models.ManyToManyField(blank=True, related_name='reglament_access', to='accounts.Position', verbose_name='Уровень доступа')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'регламент',
                'verbose_name_plural': 'Регламенты',
            },
        ),
        migrations.CreateModel(
            name='Traineeship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('day', models.PositiveIntegerField(blank=True, null=True, verbose_name='День')),
                ('img', models.ImageField(blank=True, default='default-traineeship.png', upload_to=departments.models.save, verbose_name='Фото урока')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('access', models.ManyToManyField(blank=True, related_name='traineeship_access', to='accounts.Position', verbose_name='Уровень доступа')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='Подразделение')),
                ('next_url', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='departments.traineeship', verbose_name='Следующий урок')),
                ('prev_url', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev', to='departments.traineeship', verbose_name='Предыдущий урок')),
            ],
            options={
                'verbose_name': 'стажировка',
                'verbose_name_plural': 'Стажировка',
            },
        ),
        migrations.CreateModel(
            name='VideoTraineeship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=departments.models.save, validators=[config.validators.validate_video], verbose_name='Видео')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('parent_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='departments.traineeship', verbose_name='Родительская модель')),
            ],
            options={
                'verbose_name': 'видео',
                'verbose_name_plural': 'Видео',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoDepartmentReglament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=departments.models.save, validators=[config.validators.validate_video], verbose_name='Видео')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('parent_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='departments.departmentreglament', verbose_name='Родительская модель')),
            ],
            options={
                'verbose_name': 'видео',
                'verbose_name_plural': 'Видео',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('file', models.FileField(upload_to=departments.models.save, validators=[config.validators.validate_file], verbose_name='PDF файл')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='departments.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'презентация',
                'verbose_name_plural': 'Презентация',
            },
        ),
        migrations.CreateModel(
            name='PDFTraineeship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to=departments.models.save, validators=[config.validators.validate_pdf], verbose_name='PDF файл')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('parent_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='departments.traineeship', verbose_name='Родительская модель')),
            ],
            options={
                'verbose_name': 'pdf',
                'verbose_name_plural': 'PDF',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PDFDepartmentReglament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to=departments.models.save, validators=[config.validators.validate_pdf], verbose_name='PDF файл')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('parent_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='departments.departmentreglament', verbose_name='Родительская модель')),
            ],
            options={
                'verbose_name': 'pdf',
                'verbose_name_plural': 'PDF',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageTraineeship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=departments.models.save, verbose_name='Фото')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('parent_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='departments.traineeship', verbose_name='Родительская модель')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'Фото',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageDepartmentReglament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=departments.models.save, verbose_name='Фото')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('parent_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='departments.departmentreglament', verbose_name='Родительская модель')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'Фото',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Биография')),
                ('image', models.ImageField(default='default-profile-pic.jpg', upload_to=departments.models.save, verbose_name='Фото')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='departments.department', verbose_name='Подразделение')),
                ('position', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
