# Generated by Django 4.0.2 on 2022-02-26 08:03

import ckeditor_uploader.fields
import config.validators
import departments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('departments', '0002_alter_department_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('access', models.ManyToManyField(blank=True, to='accounts.Position', verbose_name='Уровень доступа')),
            ],
            options={
                'verbose_name': 'повышение квалификации',
                'verbose_name_plural': 'Повышение квалификации',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('access', models.ManyToManyField(blank=True, to='accounts.Position', verbose_name='Уровень доступа')),
            ],
            options={
                'verbose_name': 'обучение',
                'verbose_name_plural': 'Обучение',
            },
        ),
        migrations.CreateModel(
            name='VideoTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=departments.models.save, validators=[config.validators.validate_video], verbose_name='Видео')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('parent_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='departments.training', verbose_name='Родительская модель')),
            ],
            options={
                'verbose_name': 'видео',
                'verbose_name_plural': 'Видео',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoLevelUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=departments.models.save, validators=[config.validators.validate_video], verbose_name='Видео')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('parent_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='departments.levelup', verbose_name='Родительская модель')),
            ],
            options={
                'verbose_name': 'видео',
                'verbose_name_plural': 'Видео',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PDFTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to=departments.models.save, validators=[config.validators.validate_pdf], verbose_name='PDF файл')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('parent_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='departments.training', verbose_name='Родительская модель')),
            ],
            options={
                'verbose_name': 'pdf',
                'verbose_name_plural': 'PDF',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PDFLevelUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to=departments.models.save, validators=[config.validators.validate_pdf], verbose_name='PDF файл')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('parent_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='departments.levelup', verbose_name='Родительская модель')),
            ],
            options={
                'verbose_name': 'pdf',
                'verbose_name_plural': 'PDF',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=departments.models.save, verbose_name='Фото')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('parent_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='departments.training', verbose_name='Родительская модель')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'Фото',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageLevelUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=departments.models.save, verbose_name='Фото')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('parent_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='departments.levelup', verbose_name='Родительская модель')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'Фото',
                'abstract': False,
            },
        ),
    ]
