# Generated by Django 4.0.2 on 2022-02-26 08:35

import departments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_levelup_training_videotraining_videolevelup_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'подразделение', 'verbose_name_plural': '       Подразделения'},
        ),
        migrations.AlterModelOptions(
            name='departmentreglament',
            options={'verbose_name': 'регламент', 'verbose_name_plural': '    Регламенты'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'сотрудник', 'verbose_name_plural': '      Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='presentation',
            options={'verbose_name': 'презентация', 'verbose_name_plural': '     Презентация'},
        ),
        migrations.AlterModelOptions(
            name='traineeship',
            options={'verbose_name': 'стажировка', 'verbose_name_plural': '   Стажировка'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'обучение', 'verbose_name_plural': ' Обучение'},
        ),
        migrations.AddField(
            model_name='levelup',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='Подразделение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='levelup',
            name='img',
            field=models.ImageField(blank=True, default='default-traineeship.png', upload_to=departments.models.save, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='training',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='Подразделение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='img',
            field=models.ImageField(blank=True, default='default-traineeship.png', upload_to=departments.models.save, verbose_name='Фото'),
        ),
    ]
