# Generated by Django 4.0.2 on 2022-03-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('departments', '0004_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='access',
            field=models.ManyToManyField(blank=True, to='accounts.Position', verbose_name='Уровень доступа'),
        ),
    ]
